resume: false
device: cuda:1
use_amp: false
seed: 100000
dataset_repo_id: maze2d
dataset_root: ./maze2d-large-sparse-v1.hdf5
video_backend: pyav
training:
  offline_steps: 100000
  num_workers: 4
  batch_size: 256
  eval_freq: 0
  log_freq: 250
  save_checkpoint: true
  save_freq: 5000
  online_steps: 0
  online_rollout_n_episodes: 1
  online_rollout_batch_size: 1
  online_steps_between_rollouts: 1
  online_sampling_ratio: 0.5
  online_env_seed: null
  online_buffer_capacity: null
  online_buffer_seed_size: 0
  do_online_rollout_async: false
  image_transforms:
    enable: false
    max_num_transforms: 3
    random_order: false
    brightness:
      weight: 1
      min_max:
      - 0.8
      - 1.2
    contrast:
      weight: 1
      min_max:
      - 0.8
      - 1.2
    saturation:
      weight: 1
      min_max:
      - 0.5
      - 1.5
    hue:
      weight: 1
      min_max:
      - -0.05
      - 0.05
    sharpness:
      weight: 1
      min_max:
      - 0.8
      - 1.2
  grad_clip_norm: 10
  lr: 0.0001
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas:
  - 0.95
  - 0.999
  adam_eps: 1.0e-08
  adam_weight_decay: 1.0e-06
  delta_timestamps:
    observation.environment_state:
    - -0.1
    - 0.0
    observation.state:
    - -0.1
    - 0.0
    action:
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - 2.0
    - 2.1
    - 2.2
    - 2.3
    - 2.4
    - 2.5
    - 2.6
    - 2.7
    - 2.8
    - 2.9
    - 3.0
    - 3.1
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - 4.0
    - 4.1
    - 4.2
    - 4.3
    - 4.4
    - 4.5
    - 4.6
    - 4.7
    - 4.8
    - 4.9
    - 5.0
    - 5.1
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 5.7
    - 5.8
    - 5.9
    - 6.0
    - 6.1
    - 6.2
  drop_n_last_frames: 7
eval:
  n_episodes: 50
  batch_size: 50
  use_async_envs: false
wandb:
  enable: true
  disable_artifact: false
  project: lerobot
  notes: ''
fps: 10
env:
  name: maze2d
  task: null
  state_dim: 2
  action_dim: 2
  fps: ${fps}
policy:
  name: diffusion
  n_obs_steps: 2
  horizon: 64
  n_action_steps: 8
  input_shapes:
    observation.environment_state:
    - 2
    observation.state:
    - ${env.state_dim}
  output_shapes:
    action:
    - ${env.action_dim}
  input_normalization_modes:
    observation.environment_state: min_max
    observation.state: min_max
  output_normalization_modes:
    action: min_max
  vision_backbone: resnet18
  crop_shape:
  - 84
  - 84
  crop_is_random: true
  pretrained_backbone_weights: null
  use_group_norm: true
  spatial_softmax_num_keypoints: 32
  down_dims:
  - 128
  - 256
  - 512
  kernel_size: 5
  n_groups: 8
  diffusion_step_embed_dim: 128
  use_film_scale_modulation: true
  noise_scheduler_type: DDIM
  num_train_timesteps: 100
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon
  clip_sample: true
  clip_sample_range: 1.0
  num_inference_steps: 10
  do_mask_loss_for_padding: false
  supervise_energy_landscape: true
